// <auto-generated />
namespace Hennery.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class uoo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(uoo));
        
        string IMigrationMetadata.Id
        {
            get { return "201905011914491_uoo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
